# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_trees_dialog.ui'
#
# Created: Tue Jul 21 16:36:19 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_selectTreesDockWidget(object):
    def setupUi(self, selectTreesDockWidget):
        selectTreesDockWidget.setObjectName(_fromUtf8("selectTreesDockWidget"))
        selectTreesDockWidget.resize(313, 310)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(selectTreesDockWidget.sizePolicy().hasHeightForWidth())
        selectTreesDockWidget.setSizePolicy(sizePolicy)
        selectTreesDockWidget.setMinimumSize(QtCore.QSize(280, 306))
        selectTreesDockWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Catalan, QtCore.QLocale.Spain))
        selectTreesDockWidget.setFloating(True)
        selectTreesDockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        selectTreesDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.contents = QtGui.QWidget()
        self.contents.setObjectName(_fromUtf8("contents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.contents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, -1, 5, 10)
        self.formLayout.setVerticalSpacing(8)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblHeader = QtGui.QLabel(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeader.setFont(font)
        self.lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeader.setObjectName(_fromUtf8("lblHeader"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.lblHeader)
        self.lblField2 = QtGui.QLabel(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.lblField2.setFont(font)
        self.lblField2.setObjectName(_fromUtf8("lblField2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblField2)
        self.cboField2 = SearchableComboBox(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.cboField2.setFont(font)
        self.cboField2.setObjectName(_fromUtf8("cboField2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cboField2)
        self.lblField3 = QtGui.QLabel(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.lblField3.setFont(font)
        self.lblField3.setObjectName(_fromUtf8("lblField3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblField3)
        self.cboField3 = SearchableComboBox(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.cboField3.setFont(font)
        self.cboField3.setObjectName(_fromUtf8("cboField3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cboField3)
        self.lblField4 = QtGui.QLabel(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.lblField4.setFont(font)
        self.lblField4.setObjectName(_fromUtf8("lblField4"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblField4)
        self.cboField4 = SearchableComboBox(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.cboField4.setFont(font)
        self.cboField4.setObjectName(_fromUtf8("cboField4"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.cboField4)
        self.lblField5 = QtGui.QLabel(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.lblField5.setFont(font)
        self.lblField5.setObjectName(_fromUtf8("lblField5"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lblField5)
        self.cboField5 = SearchableComboBox(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.cboField5.setFont(font)
        self.cboField5.setObjectName(_fromUtf8("cboField5"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.cboField5)
        self.cboField1 = SearchableComboBox(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.cboField1.setFont(font)
        self.cboField1.setObjectName(_fromUtf8("cboField1"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cboField1)
        self.lblField1 = QtGui.QLabel(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.lblField1.setFont(font)
        self.lblField1.setObjectName(_fromUtf8("lblField1"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblField1)
        self.cboField0 = SearchableComboBox(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.cboField0.setFont(font)
        self.cboField0.setObjectName(_fromUtf8("cboField0"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cboField0)
        self.lblField0 = QtGui.QLabel(self.contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.lblField0.setFont(font)
        self.lblField0.setObjectName(_fromUtf8("lblField0"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblField0)
        self.verticalLayout.addLayout(self.formLayout)
        self.btnReset = QtGui.QPushButton(self.contents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReset.sizePolicy().hasHeightForWidth())
        self.btnReset.setSizePolicy(sizePolicy)
        self.btnReset.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnReset.setFont(font)
        self.btnReset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.verticalLayout.addWidget(self.btnReset)
        self.lblCountSelect = QtGui.QLabel(self.contents)
        self.lblCountSelect.setMinimumSize(QtCore.QSize(200, 0))
        self.lblCountSelect.setObjectName(_fromUtf8("lblCountSelect"))
        self.verticalLayout.addWidget(self.lblCountSelect)
        selectTreesDockWidget.setWidget(self.contents)

        self.retranslateUi(selectTreesDockWidget)
        QtCore.QMetaObject.connectSlotsByName(selectTreesDockWidget)

    def retranslateUi(self, selectTreesDockWidget):
        selectTreesDockWidget.setWindowTitle(_translate("selectTreesDockWidget", "Select trees", None))
        self.lblHeader.setText(_translate("selectTreesDockWidget", "Selector d\'arbres", None))
        self.lblField2.setText(_translate("selectTreesDockWidget", "Field2", None))
        self.lblField3.setText(_translate("selectTreesDockWidget", "Field3", None))
        self.lblField4.setText(_translate("selectTreesDockWidget", "Field4", None))
        self.lblField5.setText(_translate("selectTreesDockWidget", "Field5", None))
        self.lblField1.setText(_translate("selectTreesDockWidget", "Field1", None))
        self.lblField0.setText(_translate("selectTreesDockWidget", "Field0", None))
        self.btnReset.setToolTip(_translate("selectTreesDockWidget", "Neteja la selecció", None))
        self.btnReset.setText(_translate("selectTreesDockWidget", "Reset", None))
        self.lblCountSelect.setText(_translate("selectTreesDockWidget", "Seleccionats 0 de N arbres", None))

from custom_widgets.searchable_combobox import SearchableComboBox
